// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: quiz.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuizService_CreateTemplate_FullMethodName            = "/quiz.QuizService/CreateTemplate"
	QuizService_GetTemplate_FullMethodName               = "/quiz.QuizService/GetTemplate"
	QuizService_GetTemplates_FullMethodName              = "/quiz.QuizService/GetTemplates"
	QuizService_UpdateTemplate_FullMethodName            = "/quiz.QuizService/UpdateTemplate"
	QuizService_DeleteTemplate_FullMethodName            = "/quiz.QuizService/DeleteTemplate"
	QuizService_CreateInstance_FullMethodName            = "/quiz.QuizService/CreateInstance"
	QuizService_GetInstance_FullMethodName               = "/quiz.QuizService/GetInstance"
	QuizService_GetInstanceByAccessCode_FullMethodName   = "/quiz.QuizService/GetInstanceByAccessCode"
	QuizService_GetHostingInstances_FullMethodName       = "/quiz.QuizService/GetHostingInstances"
	QuizService_GetParticipatingInstances_FullMethodName = "/quiz.QuizService/GetParticipatingInstances"
	QuizService_GetInstanceParticipants_FullMethodName   = "/quiz.QuizService/GetInstanceParticipants"
	QuizService_GetParticipantAnswers_FullMethodName     = "/quiz.QuizService/GetParticipantAnswers"
	QuizService_GradeAnswer_FullMethodName               = "/quiz.QuizService/GradeAnswer"
	QuizService_PublishResults_FullMethodName            = "/quiz.QuizService/PublishResults"
)

// QuizServiceClient is the client API for QuizService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuizServiceClient interface {
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error)
	GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*GetTemplateResponse, error)
	GetTemplates(ctx context.Context, in *GetTemplatesRequest, opts ...grpc.CallOption) (*GetTemplatesResponse, error)
	UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*UpdateTemplateResponse, error)
	DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error)
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	GetInstanceByAccessCode(ctx context.Context, in *GetInstanceByAccessCodeRequest, opts ...grpc.CallOption) (*GetInstanceByAccessCodeResponse, error)
	GetHostingInstances(ctx context.Context, in *GetHostingInstancesRequest, opts ...grpc.CallOption) (*GetHostingInstancesResponse, error)
	GetParticipatingInstances(ctx context.Context, in *GetParticipatingInstancesRequest, opts ...grpc.CallOption) (*GetParticipatingInstancesResponse, error)
	GetInstanceParticipants(ctx context.Context, in *GetInstanceParticipantsRequest, opts ...grpc.CallOption) (*GetInstanceParticipantsResponse, error)
	GetParticipantAnswers(ctx context.Context, in *GetParticipantAnswersRequest, opts ...grpc.CallOption) (*GetParticipantAnswersResponse, error)
	GradeAnswer(ctx context.Context, in *GradeAnswerRequest, opts ...grpc.CallOption) (*GradeAnswerResponse, error)
	PublishResults(ctx context.Context, in *PublishResultsRequest, opts ...grpc.CallOption) (*PublishResultsResponse, error)
}

type quizServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuizServiceClient(cc grpc.ClientConnInterface) QuizServiceClient {
	return &quizServiceClient{cc}
}

func (c *quizServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTemplateResponse)
	err := c.cc.Invoke(ctx, QuizService_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*GetTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTemplateResponse)
	err := c.cc.Invoke(ctx, QuizService_GetTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) GetTemplates(ctx context.Context, in *GetTemplatesRequest, opts ...grpc.CallOption) (*GetTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTemplatesResponse)
	err := c.cc.Invoke(ctx, QuizService_GetTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*UpdateTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTemplateResponse)
	err := c.cc.Invoke(ctx, QuizService_UpdateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTemplateResponse)
	err := c.cc.Invoke(ctx, QuizService_DeleteTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, QuizService_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, QuizService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) GetInstanceByAccessCode(ctx context.Context, in *GetInstanceByAccessCodeRequest, opts ...grpc.CallOption) (*GetInstanceByAccessCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceByAccessCodeResponse)
	err := c.cc.Invoke(ctx, QuizService_GetInstanceByAccessCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) GetHostingInstances(ctx context.Context, in *GetHostingInstancesRequest, opts ...grpc.CallOption) (*GetHostingInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostingInstancesResponse)
	err := c.cc.Invoke(ctx, QuizService_GetHostingInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) GetParticipatingInstances(ctx context.Context, in *GetParticipatingInstancesRequest, opts ...grpc.CallOption) (*GetParticipatingInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetParticipatingInstancesResponse)
	err := c.cc.Invoke(ctx, QuizService_GetParticipatingInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) GetInstanceParticipants(ctx context.Context, in *GetInstanceParticipantsRequest, opts ...grpc.CallOption) (*GetInstanceParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceParticipantsResponse)
	err := c.cc.Invoke(ctx, QuizService_GetInstanceParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) GetParticipantAnswers(ctx context.Context, in *GetParticipantAnswersRequest, opts ...grpc.CallOption) (*GetParticipantAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetParticipantAnswersResponse)
	err := c.cc.Invoke(ctx, QuizService_GetParticipantAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) GradeAnswer(ctx context.Context, in *GradeAnswerRequest, opts ...grpc.CallOption) (*GradeAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeAnswerResponse)
	err := c.cc.Invoke(ctx, QuizService_GradeAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) PublishResults(ctx context.Context, in *PublishResultsRequest, opts ...grpc.CallOption) (*PublishResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResultsResponse)
	err := c.cc.Invoke(ctx, QuizService_PublishResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuizServiceServer is the server API for QuizService service.
// All implementations must embed UnimplementedQuizServiceServer
// for forward compatibility.
type QuizServiceServer interface {
	CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateTemplateResponse, error)
	GetTemplate(context.Context, *GetTemplateRequest) (*GetTemplateResponse, error)
	GetTemplates(context.Context, *GetTemplatesRequest) (*GetTemplatesResponse, error)
	UpdateTemplate(context.Context, *UpdateTemplateRequest) (*UpdateTemplateResponse, error)
	DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error)
	CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	GetInstanceByAccessCode(context.Context, *GetInstanceByAccessCodeRequest) (*GetInstanceByAccessCodeResponse, error)
	GetHostingInstances(context.Context, *GetHostingInstancesRequest) (*GetHostingInstancesResponse, error)
	GetParticipatingInstances(context.Context, *GetParticipatingInstancesRequest) (*GetParticipatingInstancesResponse, error)
	GetInstanceParticipants(context.Context, *GetInstanceParticipantsRequest) (*GetInstanceParticipantsResponse, error)
	GetParticipantAnswers(context.Context, *GetParticipantAnswersRequest) (*GetParticipantAnswersResponse, error)
	GradeAnswer(context.Context, *GradeAnswerRequest) (*GradeAnswerResponse, error)
	PublishResults(context.Context, *PublishResultsRequest) (*PublishResultsResponse, error)
	mustEmbedUnimplementedQuizServiceServer()
}

// UnimplementedQuizServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuizServiceServer struct{}

func (UnimplementedQuizServiceServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedQuizServiceServer) GetTemplate(context.Context, *GetTemplateRequest) (*GetTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTemplate not implemented")
}
func (UnimplementedQuizServiceServer) GetTemplates(context.Context, *GetTemplatesRequest) (*GetTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTemplates not implemented")
}
func (UnimplementedQuizServiceServer) UpdateTemplate(context.Context, *UpdateTemplateRequest) (*UpdateTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedQuizServiceServer) DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedQuizServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedQuizServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedQuizServiceServer) GetInstanceByAccessCode(context.Context, *GetInstanceByAccessCodeRequest) (*GetInstanceByAccessCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstanceByAccessCode not implemented")
}
func (UnimplementedQuizServiceServer) GetHostingInstances(context.Context, *GetHostingInstancesRequest) (*GetHostingInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostingInstances not implemented")
}
func (UnimplementedQuizServiceServer) GetParticipatingInstances(context.Context, *GetParticipatingInstancesRequest) (*GetParticipatingInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParticipatingInstances not implemented")
}
func (UnimplementedQuizServiceServer) GetInstanceParticipants(context.Context, *GetInstanceParticipantsRequest) (*GetInstanceParticipantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstanceParticipants not implemented")
}
func (UnimplementedQuizServiceServer) GetParticipantAnswers(context.Context, *GetParticipantAnswersRequest) (*GetParticipantAnswersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParticipantAnswers not implemented")
}
func (UnimplementedQuizServiceServer) GradeAnswer(context.Context, *GradeAnswerRequest) (*GradeAnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GradeAnswer not implemented")
}
func (UnimplementedQuizServiceServer) PublishResults(context.Context, *PublishResultsRequest) (*PublishResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishResults not implemented")
}
func (UnimplementedQuizServiceServer) mustEmbedUnimplementedQuizServiceServer() {}
func (UnimplementedQuizServiceServer) testEmbeddedByValue()                     {}

// UnsafeQuizServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuizServiceServer will
// result in compilation errors.
type UnsafeQuizServiceServer interface {
	mustEmbedUnimplementedQuizServiceServer()
}

func RegisterQuizServiceServer(s grpc.ServiceRegistrar, srv QuizServiceServer) {
	// If the following call panics, it indicates UnimplementedQuizServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuizService_ServiceDesc, srv)
}

func _QuizService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetTemplate(ctx, req.(*GetTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_GetTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetTemplates(ctx, req.(*GetTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_UpdateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).UpdateTemplate(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).DeleteTemplate(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_GetInstanceByAccessCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceByAccessCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetInstanceByAccessCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetInstanceByAccessCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetInstanceByAccessCode(ctx, req.(*GetInstanceByAccessCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_GetHostingInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostingInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetHostingInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetHostingInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetHostingInstances(ctx, req.(*GetHostingInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_GetParticipatingInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipatingInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetParticipatingInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetParticipatingInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetParticipatingInstances(ctx, req.(*GetParticipatingInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_GetInstanceParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetInstanceParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetInstanceParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetInstanceParticipants(ctx, req.(*GetInstanceParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_GetParticipantAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipantAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetParticipantAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetParticipantAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetParticipantAnswers(ctx, req.(*GetParticipantAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_GradeAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GradeAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GradeAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GradeAnswer(ctx, req.(*GradeAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_PublishResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).PublishResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_PublishResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).PublishResults(ctx, req.(*PublishResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuizService_ServiceDesc is the grpc.ServiceDesc for QuizService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuizService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.QuizService",
	HandlerType: (*QuizServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTemplate",
			Handler:    _QuizService_CreateTemplate_Handler,
		},
		{
			MethodName: "GetTemplate",
			Handler:    _QuizService_GetTemplate_Handler,
		},
		{
			MethodName: "GetTemplates",
			Handler:    _QuizService_GetTemplates_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _QuizService_UpdateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _QuizService_DeleteTemplate_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _QuizService_CreateInstance_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _QuizService_GetInstance_Handler,
		},
		{
			MethodName: "GetInstanceByAccessCode",
			Handler:    _QuizService_GetInstanceByAccessCode_Handler,
		},
		{
			MethodName: "GetHostingInstances",
			Handler:    _QuizService_GetHostingInstances_Handler,
		},
		{
			MethodName: "GetParticipatingInstances",
			Handler:    _QuizService_GetParticipatingInstances_Handler,
		},
		{
			MethodName: "GetInstanceParticipants",
			Handler:    _QuizService_GetInstanceParticipants_Handler,
		},
		{
			MethodName: "GetParticipantAnswers",
			Handler:    _QuizService_GetParticipantAnswers_Handler,
		},
		{
			MethodName: "GradeAnswer",
			Handler:    _QuizService_GradeAnswer_Handler,
		},
		{
			MethodName: "PublishResults",
			Handler:    _QuizService_PublishResults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quiz.proto",
}
