// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: quiz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuizSyncSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizSyncSettings) Reset() {
	*x = QuizSyncSettings{}
	mi := &file_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizSyncSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizSyncSettings) ProtoMessage() {}

func (x *QuizSyncSettings) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizSyncSettings.ProtoReflect.Descriptor instead.
func (*QuizSyncSettings) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{0}
}

type QuizAsyncSettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	QuestionsRandomOrder bool                   `protobuf:"varint,1,opt,name=questions_random_order,json=questionsRandomOrder,proto3" json:"questions_random_order,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QuizAsyncSettings) Reset() {
	*x = QuizAsyncSettings{}
	mi := &file_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizAsyncSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizAsyncSettings) ProtoMessage() {}

func (x *QuizAsyncSettings) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizAsyncSettings.ProtoReflect.Descriptor instead.
func (*QuizAsyncSettings) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *QuizAsyncSettings) GetQuestionsRandomOrder() bool {
	if x != nil {
		return x.QuestionsRandomOrder
	}
	return false
}

type SingleChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []string               `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	CorrectOption int32                  `protobuf:"varint,2,opt,name=correct_option,json=correctOption,proto3" json:"correct_option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleChoice) Reset() {
	*x = SingleChoice{}
	mi := &file_quiz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleChoice) ProtoMessage() {}

func (x *SingleChoice) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleChoice.ProtoReflect.Descriptor instead.
func (*SingleChoice) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *SingleChoice) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SingleChoice) GetCorrectOption() int32 {
	if x != nil {
		return x.CorrectOption
	}
	return 0
}

type MultipleChoice struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Options        []string               `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	CorrectOptions []int32                `protobuf:"varint,2,rep,packed,name=correct_options,json=correctOptions,proto3" json:"correct_options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MultipleChoice) Reset() {
	*x = MultipleChoice{}
	mi := &file_quiz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleChoice) ProtoMessage() {}

func (x *MultipleChoice) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleChoice.ProtoReflect.Descriptor instead.
func (*MultipleChoice) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *MultipleChoice) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MultipleChoice) GetCorrectOptions() []int32 {
	if x != nil {
		return x.CorrectOptions
	}
	return nil
}

type OpenAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrectText   string                 `protobuf:"bytes,1,opt,name=correct_text,json=correctText,proto3" json:"correct_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAnswer) Reset() {
	*x = OpenAnswer{}
	mi := &file_quiz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAnswer) ProtoMessage() {}

func (x *OpenAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAnswer.ProtoReflect.Descriptor instead.
func (*OpenAnswer) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *OpenAnswer) GetCorrectText() string {
	if x != nil {
		return x.CorrectText
	}
	return ""
}

type Question struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId   string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Text         string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	OrderIndex   int32                  `protobuf:"varint,4,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	MaxScore     int32                  `protobuf:"varint,5,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	TimeLimitSec int32                  `protobuf:"varint,6,opt,name=time_limit_sec,json=timeLimitSec,proto3" json:"time_limit_sec,omitempty"`
	// Types that are valid to be assigned to Answer:
	//
	//	*Question_SingleChoice
	//	*Question_MultipleChoice
	//	*Question_OpenAnswer
	Answer        isQuestion_Answer `protobuf_oneof:"answer"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_quiz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *Question) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *Question) GetTimeLimitSec() int32 {
	if x != nil {
		return x.TimeLimitSec
	}
	return 0
}

func (x *Question) GetAnswer() isQuestion_Answer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *Question) GetSingleChoice() *SingleChoice {
	if x != nil {
		if x, ok := x.Answer.(*Question_SingleChoice); ok {
			return x.SingleChoice
		}
	}
	return nil
}

func (x *Question) GetMultipleChoice() *MultipleChoice {
	if x != nil {
		if x, ok := x.Answer.(*Question_MultipleChoice); ok {
			return x.MultipleChoice
		}
	}
	return nil
}

func (x *Question) GetOpenAnswer() *OpenAnswer {
	if x != nil {
		if x, ok := x.Answer.(*Question_OpenAnswer); ok {
			return x.OpenAnswer
		}
	}
	return nil
}

type isQuestion_Answer interface {
	isQuestion_Answer()
}

type Question_SingleChoice struct {
	SingleChoice *SingleChoice `protobuf:"bytes,7,opt,name=single_choice,json=singleChoice,proto3,oneof"`
}

type Question_MultipleChoice struct {
	MultipleChoice *MultipleChoice `protobuf:"bytes,8,opt,name=multiple_choice,json=multipleChoice,proto3,oneof"`
}

type Question_OpenAnswer struct {
	OpenAnswer *OpenAnswer `protobuf:"bytes,9,opt,name=open_answer,json=openAnswer,proto3,oneof"`
}

func (*Question_SingleChoice) isQuestion_Answer() {}

func (*Question_MultipleChoice) isQuestion_Answer() {}

func (*Question_OpenAnswer) isQuestion_Answer() {}

type QuizInstance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId     string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	AccessCode     string                 `protobuf:"bytes,4,opt,name=access_code,json=accessCode,proto3" json:"access_code,omitempty"` // 6-digit code
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                           // "waiting", "active", "finished"
	GroupId        string                 `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Deadline       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deadline,proto3" json:"deadline,omitempty"`
	QuizType       string                 `protobuf:"bytes,11,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	TotalTime      uint64                 `protobuf:"varint,13,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	TotalQuestions uint64                 `protobuf:"varint,14,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	// Types that are valid to be assigned to Settings:
	//
	//	*QuizInstance_SyncSettings
	//	*QuizInstance_AsyncSettings
	Settings      isQuizInstance_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizInstance) Reset() {
	*x = QuizInstance{}
	mi := &file_quiz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizInstance) ProtoMessage() {}

func (x *QuizInstance) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizInstance.ProtoReflect.Descriptor instead.
func (*QuizInstance) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{6}
}

func (x *QuizInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizInstance) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *QuizInstance) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuizInstance) GetAccessCode() string {
	if x != nil {
		return x.AccessCode
	}
	return ""
}

func (x *QuizInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QuizInstance) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *QuizInstance) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *QuizInstance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *QuizInstance) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QuizInstance) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *QuizInstance) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

func (x *QuizInstance) GetTotalTime() uint64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *QuizInstance) GetTotalQuestions() uint64 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

func (x *QuizInstance) GetSettings() isQuizInstance_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *QuizInstance) GetSyncSettings() *QuizSyncSettings {
	if x != nil {
		if x, ok := x.Settings.(*QuizInstance_SyncSettings); ok {
			return x.SyncSettings
		}
	}
	return nil
}

func (x *QuizInstance) GetAsyncSettings() *QuizAsyncSettings {
	if x != nil {
		if x, ok := x.Settings.(*QuizInstance_AsyncSettings); ok {
			return x.AsyncSettings
		}
	}
	return nil
}

type isQuizInstance_Settings interface {
	isQuizInstance_Settings()
}

type QuizInstance_SyncSettings struct {
	SyncSettings *QuizSyncSettings `protobuf:"bytes,15,opt,name=sync_settings,json=syncSettings,proto3,oneof"`
}

type QuizInstance_AsyncSettings struct {
	AsyncSettings *QuizAsyncSettings `protobuf:"bytes,16,opt,name=async_settings,json=asyncSettings,proto3,oneof"`
}

func (*QuizInstance_SyncSettings) isQuizInstance_Settings() {}

func (*QuizInstance_AsyncSettings) isQuizInstance_Settings() {}

type GetInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceRequest) Reset() {
	*x = GetInstanceRequest{}
	mi := &file_quiz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceRequest) ProtoMessage() {}

func (x *GetInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{7}
}

func (x *GetInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetInstanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *QuizInstance          `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Questions     []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceResponse) Reset() {
	*x = GetInstanceResponse{}
	mi := &file_quiz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceResponse) ProtoMessage() {}

func (x *GetInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceResponse.ProtoReflect.Descriptor instead.
func (*GetInstanceResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{8}
}

func (x *GetInstanceResponse) GetInstance() *QuizInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *GetInstanceResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type GetInstanceByAccessCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessCode    string                 `protobuf:"bytes,1,opt,name=access_code,json=accessCode,proto3" json:"access_code,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceByAccessCodeRequest) Reset() {
	*x = GetInstanceByAccessCodeRequest{}
	mi := &file_quiz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceByAccessCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceByAccessCodeRequest) ProtoMessage() {}

func (x *GetInstanceByAccessCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceByAccessCodeRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceByAccessCodeRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{9}
}

func (x *GetInstanceByAccessCodeRequest) GetAccessCode() string {
	if x != nil {
		return x.AccessCode
	}
	return ""
}

func (x *GetInstanceByAccessCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetInstanceByAccessCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *QuizInstance          `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	HasAccess     bool                   `protobuf:"varint,2,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceByAccessCodeResponse) Reset() {
	*x = GetInstanceByAccessCodeResponse{}
	mi := &file_quiz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceByAccessCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceByAccessCodeResponse) ProtoMessage() {}

func (x *GetInstanceByAccessCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceByAccessCodeResponse.ProtoReflect.Descriptor instead.
func (*GetInstanceByAccessCodeResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{10}
}

func (x *GetInstanceByAccessCodeResponse) GetInstance() *QuizInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *GetInstanceByAccessCodeResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *GetInstanceByAccessCodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_quiz_proto protoreflect.FileDescriptor

const file_quiz_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"quiz.proto\x12\x04quiz\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n" +
	"\x10QuizSyncSettings\"I\n" +
	"\x11QuizAsyncSettings\x124\n" +
	"\x16questions_random_order\x18\x01 \x01(\bR\x14questionsRandomOrder\"O\n" +
	"\fSingleChoice\x12\x18\n" +
	"\aoptions\x18\x01 \x03(\tR\aoptions\x12%\n" +
	"\x0ecorrect_option\x18\x02 \x01(\x05R\rcorrectOption\"S\n" +
	"\x0eMultipleChoice\x12\x18\n" +
	"\aoptions\x18\x01 \x03(\tR\aoptions\x12'\n" +
	"\x0fcorrect_options\x18\x02 \x03(\x05R\x0ecorrectOptions\"/\n" +
	"\n" +
	"OpenAnswer\x12!\n" +
	"\fcorrect_text\x18\x01 \x01(\tR\vcorrectText\"\xee\x02\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1f\n" +
	"\vorder_index\x18\x04 \x01(\x05R\n" +
	"orderIndex\x12\x1b\n" +
	"\tmax_score\x18\x05 \x01(\x05R\bmaxScore\x12$\n" +
	"\x0etime_limit_sec\x18\x06 \x01(\x05R\ftimeLimitSec\x129\n" +
	"\rsingle_choice\x18\a \x01(\v2\x12.quiz.SingleChoiceH\x00R\fsingleChoice\x12?\n" +
	"\x0fmultiple_choice\x18\b \x01(\v2\x14.quiz.MultipleChoiceH\x00R\x0emultipleChoice\x123\n" +
	"\vopen_answer\x18\t \x01(\v2\x10.quiz.OpenAnswerH\x00R\n" +
	"openAnswerB\b\n" +
	"\x06answer\"\xe8\x04\n" +
	"\fQuizInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\vaccess_code\x18\x04 \x01(\tR\n" +
	"accessCode\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x126\n" +
	"\bdeadline\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x1b\n" +
	"\tquiz_type\x18\v \x01(\tR\bquizType\x12\x1d\n" +
	"\n" +
	"total_time\x18\r \x01(\x04R\ttotalTime\x12'\n" +
	"\x0ftotal_questions\x18\x0e \x01(\x04R\x0etotalQuestions\x12=\n" +
	"\rsync_settings\x18\x0f \x01(\v2\x16.quiz.QuizSyncSettingsH\x00R\fsyncSettings\x12@\n" +
	"\x0easync_settings\x18\x10 \x01(\v2\x17.quiz.QuizAsyncSettingsH\x00R\rasyncSettingsB\n" +
	"\n" +
	"\bsettings\"N\n" +
	"\x12GetInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"s\n" +
	"\x13GetInstanceResponse\x12.\n" +
	"\binstance\x18\x01 \x01(\v2\x12.quiz.QuizInstanceR\binstance\x12,\n" +
	"\tquestions\x18\x02 \x03(\v2\x0e.quiz.QuestionR\tquestions\"Z\n" +
	"\x1eGetInstanceByAccessCodeRequest\x12\x1f\n" +
	"\vaccess_code\x18\x01 \x01(\tR\n" +
	"accessCode\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x95\x01\n" +
	"\x1fGetInstanceByAccessCodeResponse\x12.\n" +
	"\binstance\x18\x01 \x01(\v2\x12.quiz.QuizInstanceR\binstance\x12\x1d\n" +
	"\n" +
	"has_access\x18\x02 \x01(\bR\thasAccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\xb9\x01\n" +
	"\vQuizService\x12B\n" +
	"\vGetInstance\x12\x18.quiz.GetInstanceRequest\x1a\x19.quiz.GetInstanceResponse\x12f\n" +
	"\x17GetInstanceByAccessCode\x12$.quiz.GetInstanceByAccessCodeRequest\x1a%.quiz.GetInstanceByAccessCodeResponseB\x14Z\x12game-service/protob\x06proto3"

var (
	file_quiz_proto_rawDescOnce sync.Once
	file_quiz_proto_rawDescData []byte
)

func file_quiz_proto_rawDescGZIP() []byte {
	file_quiz_proto_rawDescOnce.Do(func() {
		file_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quiz_proto_rawDesc), len(file_quiz_proto_rawDesc)))
	})
	return file_quiz_proto_rawDescData
}

var file_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_quiz_proto_goTypes = []any{
	(*QuizSyncSettings)(nil),                // 0: quiz.QuizSyncSettings
	(*QuizAsyncSettings)(nil),               // 1: quiz.QuizAsyncSettings
	(*SingleChoice)(nil),                    // 2: quiz.SingleChoice
	(*MultipleChoice)(nil),                  // 3: quiz.MultipleChoice
	(*OpenAnswer)(nil),                      // 4: quiz.OpenAnswer
	(*Question)(nil),                        // 5: quiz.Question
	(*QuizInstance)(nil),                    // 6: quiz.QuizInstance
	(*GetInstanceRequest)(nil),              // 7: quiz.GetInstanceRequest
	(*GetInstanceResponse)(nil),             // 8: quiz.GetInstanceResponse
	(*GetInstanceByAccessCodeRequest)(nil),  // 9: quiz.GetInstanceByAccessCodeRequest
	(*GetInstanceByAccessCodeResponse)(nil), // 10: quiz.GetInstanceByAccessCodeResponse
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
}
var file_quiz_proto_depIdxs = []int32{
	2,  // 0: quiz.Question.single_choice:type_name -> quiz.SingleChoice
	3,  // 1: quiz.Question.multiple_choice:type_name -> quiz.MultipleChoice
	4,  // 2: quiz.Question.open_answer:type_name -> quiz.OpenAnswer
	11, // 3: quiz.QuizInstance.created_at:type_name -> google.protobuf.Timestamp
	11, // 4: quiz.QuizInstance.start_time:type_name -> google.protobuf.Timestamp
	11, // 5: quiz.QuizInstance.deadline:type_name -> google.protobuf.Timestamp
	0,  // 6: quiz.QuizInstance.sync_settings:type_name -> quiz.QuizSyncSettings
	1,  // 7: quiz.QuizInstance.async_settings:type_name -> quiz.QuizAsyncSettings
	6,  // 8: quiz.GetInstanceResponse.instance:type_name -> quiz.QuizInstance
	5,  // 9: quiz.GetInstanceResponse.questions:type_name -> quiz.Question
	6,  // 10: quiz.GetInstanceByAccessCodeResponse.instance:type_name -> quiz.QuizInstance
	7,  // 11: quiz.QuizService.GetInstance:input_type -> quiz.GetInstanceRequest
	9,  // 12: quiz.QuizService.GetInstanceByAccessCode:input_type -> quiz.GetInstanceByAccessCodeRequest
	8,  // 13: quiz.QuizService.GetInstance:output_type -> quiz.GetInstanceResponse
	10, // 14: quiz.QuizService.GetInstanceByAccessCode:output_type -> quiz.GetInstanceByAccessCodeResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_quiz_proto_init() }
func file_quiz_proto_init() {
	if File_quiz_proto != nil {
		return
	}
	file_quiz_proto_msgTypes[5].OneofWrappers = []any{
		(*Question_SingleChoice)(nil),
		(*Question_MultipleChoice)(nil),
		(*Question_OpenAnswer)(nil),
	}
	file_quiz_proto_msgTypes[6].OneofWrappers = []any{
		(*QuizInstance_SyncSettings)(nil),
		(*QuizInstance_AsyncSettings)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quiz_proto_rawDesc), len(file_quiz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quiz_proto_goTypes,
		DependencyIndexes: file_quiz_proto_depIdxs,
		MessageInfos:      file_quiz_proto_msgTypes,
	}.Build()
	File_quiz_proto = out.File
	file_quiz_proto_goTypes = nil
	file_quiz_proto_depIdxs = nil
}
