syntax = "proto3";

package quiz;

option go_package = "game-service/proto";

import "google/protobuf/timestamp.proto";

service QuizService {
  rpc GetInstance(GetInstanceRequest) returns (GetInstanceResponse);
  rpc GetInstanceByAccessCode(GetInstanceByAccessCodeRequest) returns (GetInstanceByAccessCodeResponse);
}

message QuizSyncSettings {
}

message QuizAsyncSettings {
  bool questions_random_order = 1;
}

message SingleChoice {
  repeated string options = 1;
  int32 correct_option = 2;
}

message MultipleChoice {
  repeated string options = 1;
  repeated int32 correct_options = 2;
}

message OpenAnswer {
  string correct_text = 1;
}

message Question {
  string id = 1;
  string template_id = 2;
  string text = 3;
  int32 order_index = 4;
  int32 max_score = 5;
  int32 time_limit_sec = 6;
  oneof answer {
    SingleChoice single_choice = 7;
    MultipleChoice multiple_choice = 8;
    OpenAnswer open_answer = 9;
  }
}

message QuizInstance {
  string id = 1;
  string template_id = 2;
  string title = 3;
  string access_code = 4; // 6-digit code
  string status = 5; // "waiting", "active", "finished"
  string group_id = 6;
  string created_by = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp start_time = 9;
  google.protobuf.Timestamp deadline = 10;
  string quiz_type = 11;
  uint64 total_time = 13;
  uint64 total_questions = 14;
  oneof settings {
    QuizSyncSettings sync_settings = 15;
    QuizAsyncSettings async_settings = 16;
  }
}

message GetInstanceRequest {
  string instance_id = 1;
  string user_id = 2;
}

message GetInstanceResponse {
  QuizInstance instance = 1;
  repeated Question questions = 2;
}

message GetInstanceByAccessCodeRequest {
  string access_code = 1;
  string user_id = 2;
}

message GetInstanceByAccessCodeResponse {
  QuizInstance instance = 1;
  bool has_access = 2;
  string error_message = 3;
}
