// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/user_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/user_service.go -destination=internal/service/mocks/mock_deps.go -package=mocks UserRepo,SettingsRepo,GroupRepo,FileStorage,MessagePublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	repository "user-service/internal/repository"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// GetUserByEmail mocks base method.
func (m *MockUserRepo) GetUserByEmail(ctx context.Context, email string) (*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepoMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserRepo) GetUserByID(ctx context.Context, userID string) (*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepoMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepo)(nil).GetUserByID), ctx, userID)
}

// GetUsersByEmailsMap mocks base method.
func (m *MockUserRepo) GetUsersByEmailsMap(ctx context.Context, emails []string) (map[string]*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByEmailsMap", ctx, emails)
	ret0, _ := ret[0].(map[string]*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByEmailsMap indicates an expected call of GetUsersByEmailsMap.
func (mr *MockUserRepoMockRecorder) GetUsersByEmailsMap(ctx, emails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByEmailsMap", reflect.TypeOf((*MockUserRepo)(nil).GetUsersByEmailsMap), ctx, emails)
}

// GetUsersByIDs mocks base method.
func (m *MockUserRepo) GetUsersByIDs(ctx context.Context, userIDs []string) ([]*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByIDs", ctx, userIDs)
	ret0, _ := ret[0].([]*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByIDs indicates an expected call of GetUsersByIDs.
func (mr *MockUserRepoMockRecorder) GetUsersByIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByIDs", reflect.TypeOf((*MockUserRepo)(nil).GetUsersByIDs), ctx, userIDs)
}

// UpdateUser mocks base method.
func (m *MockUserRepo) UpdateUser(ctx context.Context, user *repository.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepoMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepo)(nil).UpdateUser), ctx, user)
}

// MockSettingsRepo is a mock of SettingsRepo interface.
type MockSettingsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsRepoMockRecorder
	isgomock struct{}
}

// MockSettingsRepoMockRecorder is the mock recorder for MockSettingsRepo.
type MockSettingsRepoMockRecorder struct {
	mock *MockSettingsRepo
}

// NewMockSettingsRepo creates a new mock instance.
func NewMockSettingsRepo(ctrl *gomock.Controller) *MockSettingsRepo {
	mock := &MockSettingsRepo{ctrl: ctrl}
	mock.recorder = &MockSettingsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsRepo) EXPECT() *MockSettingsRepoMockRecorder {
	return m.recorder
}

// CreateDefaultSettings mocks base method.
func (m *MockSettingsRepo) CreateDefaultSettings(ctx context.Context, userID string) (*repository.NotificationSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDefaultSettings", ctx, userID)
	ret0, _ := ret[0].(*repository.NotificationSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDefaultSettings indicates an expected call of CreateDefaultSettings.
func (mr *MockSettingsRepoMockRecorder) CreateDefaultSettings(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDefaultSettings", reflect.TypeOf((*MockSettingsRepo)(nil).CreateDefaultSettings), ctx, userID)
}

// GetOrCreateSettings mocks base method.
func (m *MockSettingsRepo) GetOrCreateSettings(ctx context.Context, userID string) (*repository.NotificationSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateSettings", ctx, userID)
	ret0, _ := ret[0].(*repository.NotificationSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateSettings indicates an expected call of GetOrCreateSettings.
func (mr *MockSettingsRepoMockRecorder) GetOrCreateSettings(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateSettings", reflect.TypeOf((*MockSettingsRepo)(nil).GetOrCreateSettings), ctx, userID)
}

// UpdateSettings mocks base method.
func (m *MockSettingsRepo) UpdateSettings(ctx context.Context, settings *repository.NotificationSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockSettingsRepoMockRecorder) UpdateSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockSettingsRepo)(nil).UpdateSettings), ctx, settings)
}

// MockGroupRepo is a mock of GroupRepo interface.
type MockGroupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRepoMockRecorder
	isgomock struct{}
}

// MockGroupRepoMockRecorder is the mock recorder for MockGroupRepo.
type MockGroupRepoMockRecorder struct {
	mock *MockGroupRepo
}

// NewMockGroupRepo creates a new mock instance.
func NewMockGroupRepo(ctrl *gomock.Controller) *MockGroupRepo {
	mock := &MockGroupRepo{ctrl: ctrl}
	mock.recorder = &MockGroupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRepo) EXPECT() *MockGroupRepoMockRecorder {
	return m.recorder
}

// AddMembers mocks base method.
func (m *MockGroupRepo) AddMembers(ctx context.Context, groupID string, userIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMembers", ctx, groupID, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMembers indicates an expected call of AddMembers.
func (mr *MockGroupRepoMockRecorder) AddMembers(ctx, groupID, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMembers", reflect.TypeOf((*MockGroupRepo)(nil).AddMembers), ctx, groupID, userIDs)
}

// CreateGroup mocks base method.
func (m *MockGroupRepo) CreateGroup(ctx context.Context, name, ownerID string) (*repository.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, name, ownerID)
	ret0, _ := ret[0].(*repository.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockGroupRepoMockRecorder) CreateGroup(ctx, name, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockGroupRepo)(nil).CreateGroup), ctx, name, ownerID)
}

// DeleteGroup mocks base method.
func (m *MockGroupRepo) DeleteGroup(ctx context.Context, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", ctx, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockGroupRepoMockRecorder) DeleteGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockGroupRepo)(nil).DeleteGroup), ctx, groupID)
}

// GetCreatedGroups mocks base method.
func (m *MockGroupRepo) GetCreatedGroups(ctx context.Context, ownerID string) ([]*repository.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreatedGroups", ctx, ownerID)
	ret0, _ := ret[0].([]*repository.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreatedGroups indicates an expected call of GetCreatedGroups.
func (mr *MockGroupRepoMockRecorder) GetCreatedGroups(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreatedGroups", reflect.TypeOf((*MockGroupRepo)(nil).GetCreatedGroups), ctx, ownerID)
}

// GetGroupByID mocks base method.
func (m *MockGroupRepo) GetGroupByID(ctx context.Context, groupID string) (*repository.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByID", ctx, groupID)
	ret0, _ := ret[0].(*repository.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByID indicates an expected call of GetGroupByID.
func (mr *MockGroupRepoMockRecorder) GetGroupByID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByID", reflect.TypeOf((*MockGroupRepo)(nil).GetGroupByID), ctx, groupID)
}

// GetGroupUsers mocks base method.
func (m *MockGroupRepo) GetGroupUsers(ctx context.Context, groupID string) ([]*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupUsers", ctx, groupID)
	ret0, _ := ret[0].([]*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupUsers indicates an expected call of GetGroupUsers.
func (mr *MockGroupRepoMockRecorder) GetGroupUsers(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupUsers", reflect.TypeOf((*MockGroupRepo)(nil).GetGroupUsers), ctx, groupID)
}

// GetMemberCount mocks base method.
func (m *MockGroupRepo) GetMemberCount(ctx context.Context, groupID string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberCount", ctx, groupID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberCount indicates an expected call of GetMemberCount.
func (mr *MockGroupRepoMockRecorder) GetMemberCount(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberCount", reflect.TypeOf((*MockGroupRepo)(nil).GetMemberCount), ctx, groupID)
}

// GetMemberIDs mocks base method.
func (m *MockGroupRepo) GetMemberIDs(ctx context.Context, groupID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberIDs", ctx, groupID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberIDs indicates an expected call of GetMemberIDs.
func (mr *MockGroupRepoMockRecorder) GetMemberIDs(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberIDs", reflect.TypeOf((*MockGroupRepo)(nil).GetMemberIDs), ctx, groupID)
}

// GetUserGroups mocks base method.
func (m *MockGroupRepo) GetUserGroups(ctx context.Context, userID string) ([]*repository.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserGroups", ctx, userID)
	ret0, _ := ret[0].([]*repository.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserGroups indicates an expected call of GetUserGroups.
func (mr *MockGroupRepoMockRecorder) GetUserGroups(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserGroups", reflect.TypeOf((*MockGroupRepo)(nil).GetUserGroups), ctx, userID)
}

// IsMember mocks base method.
func (m *MockGroupRepo) IsMember(ctx context.Context, groupID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, groupID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockGroupRepoMockRecorder) IsMember(ctx, groupID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockGroupRepo)(nil).IsMember), ctx, groupID, userID)
}

// UpdateGroup mocks base method.
func (m *MockGroupRepo) UpdateGroup(ctx context.Context, group *repository.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockGroupRepoMockRecorder) UpdateGroup(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockGroupRepo)(nil).UpdateGroup), ctx, group)
}

// MockFileStorage is a mock of FileStorage interface.
type MockFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageMockRecorder
	isgomock struct{}
}

// MockFileStorageMockRecorder is the mock recorder for MockFileStorage.
type MockFileStorageMockRecorder struct {
	mock *MockFileStorage
}

// NewMockFileStorage creates a new mock instance.
func NewMockFileStorage(ctrl *gomock.Controller) *MockFileStorage {
	mock := &MockFileStorage{ctrl: ctrl}
	mock.recorder = &MockFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorage) EXPECT() *MockFileStorageMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFileStorage) DeleteFile(ctx context.Context, bucketName, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, bucketName, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileStorageMockRecorder) DeleteFile(ctx, bucketName, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileStorage)(nil).DeleteFile), ctx, bucketName, objectName)
}

// GetPublicURL mocks base method.
func (m *MockFileStorage) GetPublicURL(bucketName, objectName string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicURL", bucketName, objectName)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPublicURL indicates an expected call of GetPublicURL.
func (mr *MockFileStorageMockRecorder) GetPublicURL(bucketName, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicURL", reflect.TypeOf((*MockFileStorage)(nil).GetPublicURL), bucketName, objectName)
}

// UploadFile mocks base method.
func (m *MockFileStorage) UploadFile(ctx context.Context, bucketName, objectName string, reader io.Reader, size int64, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, bucketName, objectName, reader, size, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFileStorageMockRecorder) UploadFile(ctx, bucketName, objectName, reader, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFileStorage)(nil).UploadFile), ctx, bucketName, objectName, reader, size, contentType)
}

// MockMessagePublisher is a mock of MessagePublisher interface.
type MockMessagePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockMessagePublisherMockRecorder
	isgomock struct{}
}

// MockMessagePublisherMockRecorder is the mock recorder for MockMessagePublisher.
type MockMessagePublisherMockRecorder struct {
	mock *MockMessagePublisher
}

// NewMockMessagePublisher creates a new mock instance.
func NewMockMessagePublisher(ctrl *gomock.Controller) *MockMessagePublisher {
	mock := &MockMessagePublisher{ctrl: ctrl}
	mock.recorder = &MockMessagePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagePublisher) EXPECT() *MockMessagePublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockMessagePublisher) Publish(ctx context.Context, queueName string, body []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, queueName, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockMessagePublisherMockRecorder) Publish(ctx, queueName, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockMessagePublisher)(nil).Publish), ctx, queueName, body)
}
