// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/notification_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/notification_service.go -destination=internal/service/mocks/mock_deps.go -package=mocks NotificationRepo,EmailSender
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	repository "notification-service/internal/repository"
	email "notification-service/pkg/email"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepo is a mock of NotificationRepo interface.
type MockNotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepoMockRecorder
	isgomock struct{}
}

// MockNotificationRepoMockRecorder is the mock recorder for MockNotificationRepo.
type MockNotificationRepoMockRecorder struct {
	mock *MockNotificationRepo
}

// NewMockNotificationRepo creates a new mock instance.
func NewMockNotificationRepo(ctrl *gomock.Controller) *MockNotificationRepo {
	mock := &MockNotificationRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepo) EXPECT() *MockNotificationRepoMockRecorder {
	return m.recorder
}

// CreateNotification mocks base method.
func (m *MockNotificationRepo) CreateNotification(ctx context.Context, notification *repository.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotification", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNotification indicates an expected call of CreateNotification.
func (mr *MockNotificationRepoMockRecorder) CreateNotification(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotification", reflect.TypeOf((*MockNotificationRepo)(nil).CreateNotification), ctx, notification)
}

// DeleteAllForUser mocks base method.
func (m *MockNotificationRepo) DeleteAllForUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllForUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllForUser indicates an expected call of DeleteAllForUser.
func (mr *MockNotificationRepoMockRecorder) DeleteAllForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllForUser", reflect.TypeOf((*MockNotificationRepo)(nil).DeleteAllForUser), ctx, userID)
}

// DeleteNotification mocks base method.
func (m *MockNotificationRepo) DeleteNotification(ctx context.Context, notificationIDs []string, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotification", ctx, notificationIDs, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotification indicates an expected call of DeleteNotification.
func (mr *MockNotificationRepoMockRecorder) DeleteNotification(ctx, notificationIDs, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotification", reflect.TypeOf((*MockNotificationRepo)(nil).DeleteNotification), ctx, notificationIDs, userID)
}

// GetNotifications mocks base method.
func (m *MockNotificationRepo) GetNotifications(ctx context.Context, userID string, limit, offset int) ([]*repository.Notification, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotifications", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*repository.Notification)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNotifications indicates an expected call of GetNotifications.
func (mr *MockNotificationRepoMockRecorder) GetNotifications(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotifications", reflect.TypeOf((*MockNotificationRepo)(nil).GetNotifications), ctx, userID, limit, offset)
}

// MarkAsRead mocks base method.
func (m *MockNotificationRepo) MarkAsRead(ctx context.Context, notificationIDs []string, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, notificationIDs, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockNotificationRepoMockRecorder) MarkAsRead(ctx, notificationIDs, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockNotificationRepo)(nil).MarkAsRead), ctx, notificationIDs, userID)
}

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
	isgomock struct{}
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// SendAuthCode mocks base method.
func (m *MockEmailSender) SendAuthCode(emailAddr, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAuthCode", emailAddr, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAuthCode indicates an expected call of SendAuthCode.
func (mr *MockEmailSenderMockRecorder) SendAuthCode(emailAddr, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAuthCode", reflect.TypeOf((*MockEmailSender)(nil).SendAuthCode), emailAddr, code)
}

// SendDeadlineReminder mocks base method.
func (m *MockEmailSender) SendDeadlineReminder(emailAddr, quizTitle, deadline, remainingTime string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDeadlineReminder", emailAddr, quizTitle, deadline, remainingTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDeadlineReminder indicates an expected call of SendDeadlineReminder.
func (mr *MockEmailSenderMockRecorder) SendDeadlineReminder(emailAddr, quizTitle, deadline, remainingTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDeadlineReminder", reflect.TypeOf((*MockEmailSender)(nil).SendDeadlineReminder), emailAddr, quizTitle, deadline, remainingTime)
}

// SendEmail mocks base method.
func (m *MockEmailSender) SendEmail(data email.EmailData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailSenderMockRecorder) SendEmail(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailSender)(nil).SendEmail), data)
}

// SendGradeChanged mocks base method.
func (m *MockEmailSender) SendGradeChanged(emailAddr, quizTitle string, score, maxScore int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendGradeChanged", emailAddr, quizTitle, score, maxScore)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendGradeChanged indicates an expected call of SendGradeChanged.
func (mr *MockEmailSenderMockRecorder) SendGradeChanged(emailAddr, quizTitle, score, maxScore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendGradeChanged", reflect.TypeOf((*MockEmailSender)(nil).SendGradeChanged), emailAddr, quizTitle, score, maxScore)
}

// SendGroupInvite mocks base method.
func (m *MockEmailSender) SendGroupInvite(emailAddr, groupName, inviterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendGroupInvite", emailAddr, groupName, inviterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendGroupInvite indicates an expected call of SendGroupInvite.
func (mr *MockEmailSenderMockRecorder) SendGroupInvite(emailAddr, groupName, inviterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendGroupInvite", reflect.TypeOf((*MockEmailSender)(nil).SendGroupInvite), emailAddr, groupName, inviterName)
}

// SendQuizCreated mocks base method.
func (m *MockEmailSender) SendQuizCreated(emailAddr, quizTitle, creatorName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendQuizCreated", emailAddr, quizTitle, creatorName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendQuizCreated indicates an expected call of SendQuizCreated.
func (mr *MockEmailSenderMockRecorder) SendQuizCreated(emailAddr, quizTitle, creatorName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendQuizCreated", reflect.TypeOf((*MockEmailSender)(nil).SendQuizCreated), emailAddr, quizTitle, creatorName)
}

// SendQuizResults mocks base method.
func (m *MockEmailSender) SendQuizResults(emailAddr, quizTitle string, score, maxScore int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendQuizResults", emailAddr, quizTitle, score, maxScore)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendQuizResults indicates an expected call of SendQuizResults.
func (mr *MockEmailSenderMockRecorder) SendQuizResults(emailAddr, quizTitle, score, maxScore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendQuizResults", reflect.TypeOf((*MockEmailSender)(nil).SendQuizResults), emailAddr, quizTitle, score, maxScore)
}
