// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: quiz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuizTemplate struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId   string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title     string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	QuizType  string                 `protobuf:"bytes,4,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"` // "sync" or "async"
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Types that are valid to be assigned to Settings:
	//
	//	*QuizTemplate_SyncSettings
	//	*QuizTemplate_AsyncSettings
	Settings      isQuizTemplate_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizTemplate) Reset() {
	*x = QuizTemplate{}
	mi := &file_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizTemplate) ProtoMessage() {}

func (x *QuizTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizTemplate.ProtoReflect.Descriptor instead.
func (*QuizTemplate) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{0}
}

func (x *QuizTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizTemplate) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *QuizTemplate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuizTemplate) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

func (x *QuizTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *QuizTemplate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *QuizTemplate) GetSettings() isQuizTemplate_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *QuizTemplate) GetSyncSettings() *QuizSyncSettings {
	if x != nil {
		if x, ok := x.Settings.(*QuizTemplate_SyncSettings); ok {
			return x.SyncSettings
		}
	}
	return nil
}

func (x *QuizTemplate) GetAsyncSettings() *QuizAsyncSettings {
	if x != nil {
		if x, ok := x.Settings.(*QuizTemplate_AsyncSettings); ok {
			return x.AsyncSettings
		}
	}
	return nil
}

type isQuizTemplate_Settings interface {
	isQuizTemplate_Settings()
}

type QuizTemplate_SyncSettings struct {
	SyncSettings *QuizSyncSettings `protobuf:"bytes,8,opt,name=sync_settings,json=syncSettings,proto3,oneof"`
}

type QuizTemplate_AsyncSettings struct {
	AsyncSettings *QuizAsyncSettings `protobuf:"bytes,9,opt,name=async_settings,json=asyncSettings,proto3,oneof"`
}

func (*QuizTemplate_SyncSettings) isQuizTemplate_Settings() {}

func (*QuizTemplate_AsyncSettings) isQuizTemplate_Settings() {}

type QuizSyncSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizSyncSettings) Reset() {
	*x = QuizSyncSettings{}
	mi := &file_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizSyncSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizSyncSettings) ProtoMessage() {}

func (x *QuizSyncSettings) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizSyncSettings.ProtoReflect.Descriptor instead.
func (*QuizSyncSettings) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{1}
}

type QuizAsyncSettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	QuestionsRandomOrder bool                   `protobuf:"varint,1,opt,name=questions_random_order,json=questionsRandomOrder,proto3" json:"questions_random_order,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QuizAsyncSettings) Reset() {
	*x = QuizAsyncSettings{}
	mi := &file_quiz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizAsyncSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizAsyncSettings) ProtoMessage() {}

func (x *QuizAsyncSettings) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizAsyncSettings.ProtoReflect.Descriptor instead.
func (*QuizAsyncSettings) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *QuizAsyncSettings) GetQuestionsRandomOrder() bool {
	if x != nil {
		return x.QuestionsRandomOrder
	}
	return false
}

type SingleChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []string               `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	CorrectOption int32                  `protobuf:"varint,2,opt,name=correct_option,json=correctOption,proto3" json:"correct_option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleChoice) Reset() {
	*x = SingleChoice{}
	mi := &file_quiz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleChoice) ProtoMessage() {}

func (x *SingleChoice) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleChoice.ProtoReflect.Descriptor instead.
func (*SingleChoice) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *SingleChoice) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SingleChoice) GetCorrectOption() int32 {
	if x != nil {
		return x.CorrectOption
	}
	return 0
}

type MultipleChoice struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Options        []string               `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	CorrectOptions []int32                `protobuf:"varint,2,rep,packed,name=correct_options,json=correctOptions,proto3" json:"correct_options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MultipleChoice) Reset() {
	*x = MultipleChoice{}
	mi := &file_quiz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleChoice) ProtoMessage() {}

func (x *MultipleChoice) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleChoice.ProtoReflect.Descriptor instead.
func (*MultipleChoice) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *MultipleChoice) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MultipleChoice) GetCorrectOptions() []int32 {
	if x != nil {
		return x.CorrectOptions
	}
	return nil
}

type OpenAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrectText   string                 `protobuf:"bytes,1,opt,name=correct_text,json=correctText,proto3" json:"correct_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAnswer) Reset() {
	*x = OpenAnswer{}
	mi := &file_quiz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAnswer) ProtoMessage() {}

func (x *OpenAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAnswer.ProtoReflect.Descriptor instead.
func (*OpenAnswer) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *OpenAnswer) GetCorrectText() string {
	if x != nil {
		return x.CorrectText
	}
	return ""
}

type Question struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId   string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Text         string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	OrderIndex   int32                  `protobuf:"varint,4,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	MaxScore     int32                  `protobuf:"varint,5,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	TimeLimitSec int32                  `protobuf:"varint,6,opt,name=time_limit_sec,json=timeLimitSec,proto3" json:"time_limit_sec,omitempty"` // 0 = no limit
	// Types that are valid to be assigned to Answer:
	//
	//	*Question_SingleChoice
	//	*Question_MultipleChoice
	//	*Question_OpenAnswer
	Answer        isQuestion_Answer `protobuf_oneof:"answer"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_quiz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{6}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *Question) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *Question) GetTimeLimitSec() int32 {
	if x != nil {
		return x.TimeLimitSec
	}
	return 0
}

func (x *Question) GetAnswer() isQuestion_Answer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *Question) GetSingleChoice() *SingleChoice {
	if x != nil {
		if x, ok := x.Answer.(*Question_SingleChoice); ok {
			return x.SingleChoice
		}
	}
	return nil
}

func (x *Question) GetMultipleChoice() *MultipleChoice {
	if x != nil {
		if x, ok := x.Answer.(*Question_MultipleChoice); ok {
			return x.MultipleChoice
		}
	}
	return nil
}

func (x *Question) GetOpenAnswer() *OpenAnswer {
	if x != nil {
		if x, ok := x.Answer.(*Question_OpenAnswer); ok {
			return x.OpenAnswer
		}
	}
	return nil
}

type isQuestion_Answer interface {
	isQuestion_Answer()
}

type Question_SingleChoice struct {
	SingleChoice *SingleChoice `protobuf:"bytes,7,opt,name=single_choice,json=singleChoice,proto3,oneof"`
}

type Question_MultipleChoice struct {
	MultipleChoice *MultipleChoice `protobuf:"bytes,8,opt,name=multiple_choice,json=multipleChoice,proto3,oneof"`
}

type Question_OpenAnswer struct {
	OpenAnswer *OpenAnswer `protobuf:"bytes,9,opt,name=open_answer,json=openAnswer,proto3,oneof"`
}

func (*Question_SingleChoice) isQuestion_Answer() {}

func (*Question_MultipleChoice) isQuestion_Answer() {}

func (*Question_OpenAnswer) isQuestion_Answer() {}

type QuizInstance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId     string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	AccessCode     string                 `protobuf:"bytes,4,opt,name=access_code,json=accessCode,proto3" json:"access_code,omitempty"` // 6-digit code
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                           // "waiting", "active", "finished"
	GroupId        string                 `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Deadline       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deadline,proto3" json:"deadline,omitempty"`
	QuizType       string                 `protobuf:"bytes,11,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	TotalTime      uint64                 `protobuf:"varint,13,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	TotalQuestions uint64                 `protobuf:"varint,14,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	// Types that are valid to be assigned to Settings:
	//
	//	*QuizInstance_SyncSettings
	//	*QuizInstance_AsyncSettings
	Settings      isQuizInstance_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizInstance) Reset() {
	*x = QuizInstance{}
	mi := &file_quiz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizInstance) ProtoMessage() {}

func (x *QuizInstance) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizInstance.ProtoReflect.Descriptor instead.
func (*QuizInstance) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{7}
}

func (x *QuizInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizInstance) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *QuizInstance) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuizInstance) GetAccessCode() string {
	if x != nil {
		return x.AccessCode
	}
	return ""
}

func (x *QuizInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QuizInstance) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *QuizInstance) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *QuizInstance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *QuizInstance) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QuizInstance) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *QuizInstance) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

func (x *QuizInstance) GetTotalTime() uint64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *QuizInstance) GetTotalQuestions() uint64 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

func (x *QuizInstance) GetSettings() isQuizInstance_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *QuizInstance) GetSyncSettings() *QuizSyncSettings {
	if x != nil {
		if x, ok := x.Settings.(*QuizInstance_SyncSettings); ok {
			return x.SyncSettings
		}
	}
	return nil
}

func (x *QuizInstance) GetAsyncSettings() *QuizAsyncSettings {
	if x != nil {
		if x, ok := x.Settings.(*QuizInstance_AsyncSettings); ok {
			return x.AsyncSettings
		}
	}
	return nil
}

type isQuizInstance_Settings interface {
	isQuizInstance_Settings()
}

type QuizInstance_SyncSettings struct {
	SyncSettings *QuizSyncSettings `protobuf:"bytes,15,opt,name=sync_settings,json=syncSettings,proto3,oneof"`
}

type QuizInstance_AsyncSettings struct {
	AsyncSettings *QuizAsyncSettings `protobuf:"bytes,16,opt,name=async_settings,json=asyncSettings,proto3,oneof"`
}

func (*QuizInstance_SyncSettings) isQuizInstance_Settings() {}

func (*QuizInstance_AsyncSettings) isQuizInstance_Settings() {}

type CreateTemplateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title     string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	QuizType  string                 `protobuf:"bytes,3,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	Questions []*QuestionInput       `protobuf:"bytes,5,rep,name=questions,proto3" json:"questions,omitempty"`
	// Types that are valid to be assigned to Settings:
	//
	//	*CreateTemplateRequest_SyncSettings
	//	*CreateTemplateRequest_AsyncSettings
	Settings      isCreateTemplateRequest_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_quiz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTemplateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTemplateRequest) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

func (x *CreateTemplateRequest) GetQuestions() []*QuestionInput {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *CreateTemplateRequest) GetSettings() isCreateTemplateRequest_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *CreateTemplateRequest) GetSyncSettings() *QuizSyncSettings {
	if x != nil {
		if x, ok := x.Settings.(*CreateTemplateRequest_SyncSettings); ok {
			return x.SyncSettings
		}
	}
	return nil
}

func (x *CreateTemplateRequest) GetAsyncSettings() *QuizAsyncSettings {
	if x != nil {
		if x, ok := x.Settings.(*CreateTemplateRequest_AsyncSettings); ok {
			return x.AsyncSettings
		}
	}
	return nil
}

type isCreateTemplateRequest_Settings interface {
	isCreateTemplateRequest_Settings()
}

type CreateTemplateRequest_SyncSettings struct {
	SyncSettings *QuizSyncSettings `protobuf:"bytes,6,opt,name=sync_settings,json=syncSettings,proto3,oneof"`
}

type CreateTemplateRequest_AsyncSettings struct {
	AsyncSettings *QuizAsyncSettings `protobuf:"bytes,7,opt,name=async_settings,json=asyncSettings,proto3,oneof"`
}

func (*CreateTemplateRequest_SyncSettings) isCreateTemplateRequest_Settings() {}

func (*CreateTemplateRequest_AsyncSettings) isCreateTemplateRequest_Settings() {}

type QuestionInput struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Text         string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	MaxScore     int32                  `protobuf:"varint,2,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	TimeLimitSec int32                  `protobuf:"varint,3,opt,name=time_limit_sec,json=timeLimitSec,proto3" json:"time_limit_sec,omitempty"`
	// Types that are valid to be assigned to Answer:
	//
	//	*QuestionInput_SingleChoice
	//	*QuestionInput_MultipleChoice
	//	*QuestionInput_OpenAnswer
	Answer        isQuestionInput_Answer `protobuf_oneof:"answer"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionInput) Reset() {
	*x = QuestionInput{}
	mi := &file_quiz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionInput) ProtoMessage() {}

func (x *QuestionInput) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionInput.ProtoReflect.Descriptor instead.
func (*QuestionInput) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{9}
}

func (x *QuestionInput) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QuestionInput) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *QuestionInput) GetTimeLimitSec() int32 {
	if x != nil {
		return x.TimeLimitSec
	}
	return 0
}

func (x *QuestionInput) GetAnswer() isQuestionInput_Answer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *QuestionInput) GetSingleChoice() *SingleChoice {
	if x != nil {
		if x, ok := x.Answer.(*QuestionInput_SingleChoice); ok {
			return x.SingleChoice
		}
	}
	return nil
}

func (x *QuestionInput) GetMultipleChoice() *MultipleChoice {
	if x != nil {
		if x, ok := x.Answer.(*QuestionInput_MultipleChoice); ok {
			return x.MultipleChoice
		}
	}
	return nil
}

func (x *QuestionInput) GetOpenAnswer() *OpenAnswer {
	if x != nil {
		if x, ok := x.Answer.(*QuestionInput_OpenAnswer); ok {
			return x.OpenAnswer
		}
	}
	return nil
}

type isQuestionInput_Answer interface {
	isQuestionInput_Answer()
}

type QuestionInput_SingleChoice struct {
	SingleChoice *SingleChoice `protobuf:"bytes,4,opt,name=single_choice,json=singleChoice,proto3,oneof"`
}

type QuestionInput_MultipleChoice struct {
	MultipleChoice *MultipleChoice `protobuf:"bytes,5,opt,name=multiple_choice,json=multipleChoice,proto3,oneof"`
}

type QuestionInput_OpenAnswer struct {
	OpenAnswer *OpenAnswer `protobuf:"bytes,6,opt,name=open_answer,json=openAnswer,proto3,oneof"`
}

func (*QuestionInput_SingleChoice) isQuestionInput_Answer() {}

func (*QuestionInput_MultipleChoice) isQuestionInput_Answer() {}

func (*QuestionInput_OpenAnswer) isQuestionInput_Answer() {}

type CreateTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *QuizTemplate          `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Questions     []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateResponse) Reset() {
	*x = CreateTemplateResponse{}
	mi := &file_quiz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateResponse) ProtoMessage() {}

func (x *CreateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTemplateResponse) GetTemplate() *QuizTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *CreateTemplateResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_quiz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{11}
}

func (x *GetTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *GetTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *QuizTemplate          `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Questions     []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateResponse) Reset() {
	*x = GetTemplateResponse{}
	mi := &file_quiz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateResponse) ProtoMessage() {}

func (x *GetTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetTemplateResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{12}
}

func (x *GetTemplateResponse) GetTemplate() *QuizTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *GetTemplateResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type GetTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplatesRequest) Reset() {
	*x = GetTemplatesRequest{}
	mi := &file_quiz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplatesRequest) ProtoMessage() {}

func (x *GetTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplatesRequest.ProtoReflect.Descriptor instead.
func (*GetTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{13}
}

func (x *GetTemplatesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TemplateWithQuestions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *QuizTemplate          `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Questions     []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateWithQuestions) Reset() {
	*x = TemplateWithQuestions{}
	mi := &file_quiz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateWithQuestions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateWithQuestions) ProtoMessage() {}

func (x *TemplateWithQuestions) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateWithQuestions.ProtoReflect.Descriptor instead.
func (*TemplateWithQuestions) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{14}
}

func (x *TemplateWithQuestions) GetTemplate() *QuizTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *TemplateWithQuestions) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type GetTemplatesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Templates     []*TemplateWithQuestions `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplatesResponse) Reset() {
	*x = GetTemplatesResponse{}
	mi := &file_quiz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplatesResponse) ProtoMessage() {}

func (x *GetTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplatesResponse.ProtoReflect.Descriptor instead.
func (*GetTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{15}
}

func (x *GetTemplatesResponse) GetTemplates() []*TemplateWithQuestions {
	if x != nil {
		return x.Templates
	}
	return nil
}

type UpdateTemplateRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TemplateId string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	UserId     string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title      string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Questions  []*QuestionInput       `protobuf:"bytes,5,rep,name=questions,proto3" json:"questions,omitempty"`
	QuizType   string                 `protobuf:"bytes,6,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	// Types that are valid to be assigned to Settings:
	//
	//	*UpdateTemplateRequest_SyncSettings
	//	*UpdateTemplateRequest_AsyncSettings
	Settings      isUpdateTemplateRequest_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_quiz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *UpdateTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTemplateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTemplateRequest) GetQuestions() []*QuestionInput {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *UpdateTemplateRequest) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

func (x *UpdateTemplateRequest) GetSettings() isUpdateTemplateRequest_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *UpdateTemplateRequest) GetSyncSettings() *QuizSyncSettings {
	if x != nil {
		if x, ok := x.Settings.(*UpdateTemplateRequest_SyncSettings); ok {
			return x.SyncSettings
		}
	}
	return nil
}

func (x *UpdateTemplateRequest) GetAsyncSettings() *QuizAsyncSettings {
	if x != nil {
		if x, ok := x.Settings.(*UpdateTemplateRequest_AsyncSettings); ok {
			return x.AsyncSettings
		}
	}
	return nil
}

type isUpdateTemplateRequest_Settings interface {
	isUpdateTemplateRequest_Settings()
}

type UpdateTemplateRequest_SyncSettings struct {
	SyncSettings *QuizSyncSettings `protobuf:"bytes,7,opt,name=sync_settings,json=syncSettings,proto3,oneof"`
}

type UpdateTemplateRequest_AsyncSettings struct {
	AsyncSettings *QuizAsyncSettings `protobuf:"bytes,8,opt,name=async_settings,json=asyncSettings,proto3,oneof"`
}

func (*UpdateTemplateRequest_SyncSettings) isUpdateTemplateRequest_Settings() {}

func (*UpdateTemplateRequest_AsyncSettings) isUpdateTemplateRequest_Settings() {}

type UpdateTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *QuizTemplate          `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Questions     []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateResponse) Reset() {
	*x = UpdateTemplateResponse{}
	mi := &file_quiz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateResponse) ProtoMessage() {}

func (x *UpdateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateResponse.ProtoReflect.Descriptor instead.
func (*UpdateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateTemplateResponse) GetTemplate() *QuizTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *UpdateTemplateResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_quiz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *DeleteTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateResponse) Reset() {
	*x = DeleteTemplateResponse{}
	mi := &file_quiz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateResponse) ProtoMessage() {}

func (x *DeleteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{19}
}

type CreateInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	GroupId       string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	mi := &file_quiz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{20}
}

func (x *CreateInstanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateInstanceRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateInstanceRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateInstanceRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateInstanceRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type CreateInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *QuizInstance          `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceResponse) Reset() {
	*x = CreateInstanceResponse{}
	mi := &file_quiz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceResponse) ProtoMessage() {}

func (x *CreateInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateInstanceResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{21}
}

func (x *CreateInstanceResponse) GetInstance() *QuizInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type GetInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceRequest) Reset() {
	*x = GetInstanceRequest{}
	mi := &file_quiz_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceRequest) ProtoMessage() {}

func (x *GetInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{22}
}

func (x *GetInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetInstanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *QuizInstance          `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Questions     []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceResponse) Reset() {
	*x = GetInstanceResponse{}
	mi := &file_quiz_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceResponse) ProtoMessage() {}

func (x *GetInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceResponse.ProtoReflect.Descriptor instead.
func (*GetInstanceResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{23}
}

func (x *GetInstanceResponse) GetInstance() *QuizInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *GetInstanceResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type GetInstanceByAccessCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessCode    string                 `protobuf:"bytes,1,opt,name=access_code,json=accessCode,proto3" json:"access_code,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceByAccessCodeRequest) Reset() {
	*x = GetInstanceByAccessCodeRequest{}
	mi := &file_quiz_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceByAccessCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceByAccessCodeRequest) ProtoMessage() {}

func (x *GetInstanceByAccessCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceByAccessCodeRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceByAccessCodeRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{24}
}

func (x *GetInstanceByAccessCodeRequest) GetAccessCode() string {
	if x != nil {
		return x.AccessCode
	}
	return ""
}

func (x *GetInstanceByAccessCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetInstanceByAccessCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *QuizInstance          `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	HasAccess     bool                   `protobuf:"varint,2,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceByAccessCodeResponse) Reset() {
	*x = GetInstanceByAccessCodeResponse{}
	mi := &file_quiz_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceByAccessCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceByAccessCodeResponse) ProtoMessage() {}

func (x *GetInstanceByAccessCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceByAccessCodeResponse.ProtoReflect.Descriptor instead.
func (*GetInstanceByAccessCodeResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{25}
}

func (x *GetInstanceByAccessCodeResponse) GetInstance() *QuizInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *GetInstanceByAccessCodeResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

type GetHostingInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "active", "pending_review", "reviewed", "" = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostingInstancesRequest) Reset() {
	*x = GetHostingInstancesRequest{}
	mi := &file_quiz_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostingInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostingInstancesRequest) ProtoMessage() {}

func (x *GetHostingInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostingInstancesRequest.ProtoReflect.Descriptor instead.
func (*GetHostingInstancesRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{26}
}

func (x *GetHostingInstancesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetHostingInstancesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetHostingInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*QuizInstance        `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostingInstancesResponse) Reset() {
	*x = GetHostingInstancesResponse{}
	mi := &file_quiz_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostingInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostingInstancesResponse) ProtoMessage() {}

func (x *GetHostingInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostingInstancesResponse.ProtoReflect.Descriptor instead.
func (*GetHostingInstancesResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{27}
}

func (x *GetHostingInstancesResponse) GetInstances() []*QuizInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type GetParticipatingInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionStatus string                 `protobuf:"bytes,2,opt,name=session_status,json=sessionStatus,proto3" json:"session_status,omitempty"` // "not_started", "joined", "in_progress", "finished", "" = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipatingInstancesRequest) Reset() {
	*x = GetParticipatingInstancesRequest{}
	mi := &file_quiz_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipatingInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipatingInstancesRequest) ProtoMessage() {}

func (x *GetParticipatingInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipatingInstancesRequest.ProtoReflect.Descriptor instead.
func (*GetParticipatingInstancesRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{28}
}

func (x *GetParticipatingInstancesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetParticipatingInstancesRequest) GetSessionStatus() string {
	if x != nil {
		return x.SessionStatus
	}
	return ""
}

type ParticipatingInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *QuizInstance          `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	SessionStatus string                 `protobuf:"bytes,2,opt,name=session_status,json=sessionStatus,proto3" json:"session_status,omitempty"` // "not_started", "joined", "in_progress", "finished"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipatingInstance) Reset() {
	*x = ParticipatingInstance{}
	mi := &file_quiz_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipatingInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipatingInstance) ProtoMessage() {}

func (x *ParticipatingInstance) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipatingInstance.ProtoReflect.Descriptor instead.
func (*ParticipatingInstance) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{29}
}

func (x *ParticipatingInstance) GetInstance() *QuizInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *ParticipatingInstance) GetSessionStatus() string {
	if x != nil {
		return x.SessionStatus
	}
	return ""
}

type GetParticipatingInstancesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Instances     []*ParticipatingInstance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipatingInstancesResponse) Reset() {
	*x = GetParticipatingInstancesResponse{}
	mi := &file_quiz_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipatingInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipatingInstancesResponse) ProtoMessage() {}

func (x *GetParticipatingInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipatingInstancesResponse.ProtoReflect.Descriptor instead.
func (*GetParticipatingInstancesResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{30}
}

func (x *GetParticipatingInstancesResponse) GetInstances() []*ParticipatingInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type ParticipantInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionStatus    string                 `protobuf:"bytes,2,opt,name=session_status,json=sessionStatus,proto3" json:"session_status,omitempty"` // "joined", "in_progress", "finished"
	ReviewStatus     string                 `protobuf:"bytes,3,opt,name=review_status,json=reviewStatus,proto3" json:"review_status,omitempty"`    // "pending_review", "reviewed"
	TotalScore       int32                  `protobuf:"varint,4,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	MaxPossibleScore int32                  `protobuf:"varint,5,opt,name=max_possible_score,json=maxPossibleScore,proto3" json:"max_possible_score,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ParticipantInfo) Reset() {
	*x = ParticipantInfo{}
	mi := &file_quiz_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantInfo) ProtoMessage() {}

func (x *ParticipantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantInfo.ProtoReflect.Descriptor instead.
func (*ParticipantInfo) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{31}
}

func (x *ParticipantInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ParticipantInfo) GetSessionStatus() string {
	if x != nil {
		return x.SessionStatus
	}
	return ""
}

func (x *ParticipantInfo) GetReviewStatus() string {
	if x != nil {
		return x.ReviewStatus
	}
	return ""
}

func (x *ParticipantInfo) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *ParticipantInfo) GetMaxPossibleScore() int32 {
	if x != nil {
		return x.MaxPossibleScore
	}
	return 0
}

type GetInstanceParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceParticipantsRequest) Reset() {
	*x = GetInstanceParticipantsRequest{}
	mi := &file_quiz_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceParticipantsRequest) ProtoMessage() {}

func (x *GetInstanceParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceParticipantsRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{32}
}

func (x *GetInstanceParticipantsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetInstanceParticipantsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetInstanceParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*ParticipantInfo     `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceParticipantsResponse) Reset() {
	*x = GetInstanceParticipantsResponse{}
	mi := &file_quiz_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceParticipantsResponse) ProtoMessage() {}

func (x *GetInstanceParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceParticipantsResponse.ProtoReflect.Descriptor instead.
func (*GetInstanceParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{33}
}

func (x *GetInstanceParticipantsResponse) GetParticipants() []*ParticipantInfo {
	if x != nil {
		return x.Participants
	}
	return nil
}

type AnswerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,3,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	TimeSpentMs   int64                  `protobuf:"varint,5,opt,name=time_spent_ms,json=timeSpentMs,proto3" json:"time_spent_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerInfo) Reset() {
	*x = AnswerInfo{}
	mi := &file_quiz_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerInfo) ProtoMessage() {}

func (x *AnswerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerInfo.ProtoReflect.Descriptor instead.
func (*AnswerInfo) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{34}
}

func (x *AnswerInfo) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *AnswerInfo) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AnswerInfo) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *AnswerInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AnswerInfo) GetTimeSpentMs() int64 {
	if x != nil {
		return x.TimeSpentMs
	}
	return 0
}

type GetParticipantAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,3,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantAnswersRequest) Reset() {
	*x = GetParticipantAnswersRequest{}
	mi := &file_quiz_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantAnswersRequest) ProtoMessage() {}

func (x *GetParticipantAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantAnswersRequest.ProtoReflect.Descriptor instead.
func (*GetParticipantAnswersRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{35}
}

func (x *GetParticipantAnswersRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetParticipantAnswersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetParticipantAnswersRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

type GetParticipantAnswersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *QuizInstance          `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Questions     []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	Answers       []*AnswerInfo          `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantAnswersResponse) Reset() {
	*x = GetParticipantAnswersResponse{}
	mi := &file_quiz_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantAnswersResponse) ProtoMessage() {}

func (x *GetParticipantAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantAnswersResponse.ProtoReflect.Descriptor instead.
func (*GetParticipantAnswersResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{36}
}

func (x *GetParticipantAnswersResponse) GetInstance() *QuizInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *GetParticipantAnswersResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *GetParticipantAnswersResponse) GetAnswers() []*AnswerInfo {
	if x != nil {
		return x.Answers
	}
	return nil
}

type GradeAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,3,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	QuestionId    string                 `protobuf:"bytes,4,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Score         int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeAnswerRequest) Reset() {
	*x = GradeAnswerRequest{}
	mi := &file_quiz_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeAnswerRequest) ProtoMessage() {}

func (x *GradeAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeAnswerRequest.ProtoReflect.Descriptor instead.
func (*GradeAnswerRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{37}
}

func (x *GradeAnswerRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GradeAnswerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GradeAnswerRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *GradeAnswerRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *GradeAnswerRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GradeAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeAnswerResponse) Reset() {
	*x = GradeAnswerResponse{}
	mi := &file_quiz_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeAnswerResponse) ProtoMessage() {}

func (x *GradeAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeAnswerResponse.ProtoReflect.Descriptor instead.
func (*GradeAnswerResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{38}
}

type PublishResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResultsRequest) Reset() {
	*x = PublishResultsRequest{}
	mi := &file_quiz_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResultsRequest) ProtoMessage() {}

func (x *PublishResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResultsRequest.ProtoReflect.Descriptor instead.
func (*PublishResultsRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{39}
}

func (x *PublishResultsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *PublishResultsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PublishResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResultsResponse) Reset() {
	*x = PublishResultsResponse{}
	mi := &file_quiz_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResultsResponse) ProtoMessage() {}

func (x *PublishResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResultsResponse.ProtoReflect.Descriptor instead.
func (*PublishResultsResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{40}
}

var File_quiz_proto protoreflect.FileDescriptor

const file_quiz_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"quiz.proto\x12\x04quiz\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x02\n" +
	"\fQuizTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\tquiz_type\x18\x04 \x01(\tR\bquizType\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\rsync_settings\x18\b \x01(\v2\x16.quiz.QuizSyncSettingsH\x00R\fsyncSettings\x12@\n" +
	"\x0easync_settings\x18\t \x01(\v2\x17.quiz.QuizAsyncSettingsH\x00R\rasyncSettingsB\n" +
	"\n" +
	"\bsettings\"\x12\n" +
	"\x10QuizSyncSettings\"I\n" +
	"\x11QuizAsyncSettings\x124\n" +
	"\x16questions_random_order\x18\x01 \x01(\bR\x14questionsRandomOrder\"O\n" +
	"\fSingleChoice\x12\x18\n" +
	"\aoptions\x18\x01 \x03(\tR\aoptions\x12%\n" +
	"\x0ecorrect_option\x18\x02 \x01(\x05R\rcorrectOption\"S\n" +
	"\x0eMultipleChoice\x12\x18\n" +
	"\aoptions\x18\x01 \x03(\tR\aoptions\x12'\n" +
	"\x0fcorrect_options\x18\x02 \x03(\x05R\x0ecorrectOptions\"/\n" +
	"\n" +
	"OpenAnswer\x12!\n" +
	"\fcorrect_text\x18\x01 \x01(\tR\vcorrectText\"\xee\x02\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1f\n" +
	"\vorder_index\x18\x04 \x01(\x05R\n" +
	"orderIndex\x12\x1b\n" +
	"\tmax_score\x18\x05 \x01(\x05R\bmaxScore\x12$\n" +
	"\x0etime_limit_sec\x18\x06 \x01(\x05R\ftimeLimitSec\x129\n" +
	"\rsingle_choice\x18\a \x01(\v2\x12.quiz.SingleChoiceH\x00R\fsingleChoice\x12?\n" +
	"\x0fmultiple_choice\x18\b \x01(\v2\x14.quiz.MultipleChoiceH\x00R\x0emultipleChoice\x123\n" +
	"\vopen_answer\x18\t \x01(\v2\x10.quiz.OpenAnswerH\x00R\n" +
	"openAnswerB\b\n" +
	"\x06answer\"\xe8\x04\n" +
	"\fQuizInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\vaccess_code\x18\x04 \x01(\tR\n" +
	"accessCode\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x126\n" +
	"\bdeadline\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x1b\n" +
	"\tquiz_type\x18\v \x01(\tR\bquizType\x12\x1d\n" +
	"\n" +
	"total_time\x18\r \x01(\x04R\ttotalTime\x12'\n" +
	"\x0ftotal_questions\x18\x0e \x01(\x04R\x0etotalQuestions\x12=\n" +
	"\rsync_settings\x18\x0f \x01(\v2\x16.quiz.QuizSyncSettingsH\x00R\fsyncSettings\x12@\n" +
	"\x0easync_settings\x18\x10 \x01(\v2\x17.quiz.QuizAsyncSettingsH\x00R\rasyncSettingsB\n" +
	"\n" +
	"\bsettings\"\xa3\x02\n" +
	"\x15CreateTemplateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tquiz_type\x18\x03 \x01(\tR\bquizType\x121\n" +
	"\tquestions\x18\x05 \x03(\v2\x13.quiz.QuestionInputR\tquestions\x12=\n" +
	"\rsync_settings\x18\x06 \x01(\v2\x16.quiz.QuizSyncSettingsH\x00R\fsyncSettings\x12@\n" +
	"\x0easync_settings\x18\a \x01(\v2\x17.quiz.QuizAsyncSettingsH\x00R\rasyncSettingsB\n" +
	"\n" +
	"\bsettings\"\xa1\x02\n" +
	"\rQuestionInput\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\tmax_score\x18\x02 \x01(\x05R\bmaxScore\x12$\n" +
	"\x0etime_limit_sec\x18\x03 \x01(\x05R\ftimeLimitSec\x129\n" +
	"\rsingle_choice\x18\x04 \x01(\v2\x12.quiz.SingleChoiceH\x00R\fsingleChoice\x12?\n" +
	"\x0fmultiple_choice\x18\x05 \x01(\v2\x14.quiz.MultipleChoiceH\x00R\x0emultipleChoice\x123\n" +
	"\vopen_answer\x18\x06 \x01(\v2\x10.quiz.OpenAnswerH\x00R\n" +
	"openAnswerB\b\n" +
	"\x06answer\"v\n" +
	"\x16CreateTemplateResponse\x12.\n" +
	"\btemplate\x18\x01 \x01(\v2\x12.quiz.QuizTemplateR\btemplate\x12,\n" +
	"\tquestions\x18\x02 \x03(\v2\x0e.quiz.QuestionR\tquestions\"N\n" +
	"\x12GetTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"s\n" +
	"\x13GetTemplateResponse\x12.\n" +
	"\btemplate\x18\x01 \x01(\v2\x12.quiz.QuizTemplateR\btemplate\x12,\n" +
	"\tquestions\x18\x02 \x03(\v2\x0e.quiz.QuestionR\tquestions\".\n" +
	"\x13GetTemplatesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"u\n" +
	"\x15TemplateWithQuestions\x12.\n" +
	"\btemplate\x18\x01 \x01(\v2\x12.quiz.QuizTemplateR\btemplate\x12,\n" +
	"\tquestions\x18\x02 \x03(\v2\x0e.quiz.QuestionR\tquestions\"Q\n" +
	"\x14GetTemplatesResponse\x129\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1b.quiz.TemplateWithQuestionsR\ttemplates\"\xc4\x02\n" +
	"\x15UpdateTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x121\n" +
	"\tquestions\x18\x05 \x03(\v2\x13.quiz.QuestionInputR\tquestions\x12\x1b\n" +
	"\tquiz_type\x18\x06 \x01(\tR\bquizType\x12=\n" +
	"\rsync_settings\x18\a \x01(\v2\x16.quiz.QuizSyncSettingsH\x00R\fsyncSettings\x12@\n" +
	"\x0easync_settings\x18\b \x01(\v2\x17.quiz.QuizAsyncSettingsH\x00R\rasyncSettingsB\n" +
	"\n" +
	"\bsettings\"v\n" +
	"\x16UpdateTemplateResponse\x12.\n" +
	"\btemplate\x18\x01 \x01(\v2\x12.quiz.QuizTemplateR\btemplate\x12,\n" +
	"\tquestions\x18\x02 \x03(\v2\x0e.quiz.QuestionR\tquestions\"Q\n" +
	"\x15DeleteTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x18\n" +
	"\x16DeleteTemplateResponse\"\xba\x01\n" +
	"\x15CreateInstanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"H\n" +
	"\x16CreateInstanceResponse\x12.\n" +
	"\binstance\x18\x01 \x01(\v2\x12.quiz.QuizInstanceR\binstance\"N\n" +
	"\x12GetInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"s\n" +
	"\x13GetInstanceResponse\x12.\n" +
	"\binstance\x18\x01 \x01(\v2\x12.quiz.QuizInstanceR\binstance\x12,\n" +
	"\tquestions\x18\x02 \x03(\v2\x0e.quiz.QuestionR\tquestions\"Z\n" +
	"\x1eGetInstanceByAccessCodeRequest\x12\x1f\n" +
	"\vaccess_code\x18\x01 \x01(\tR\n" +
	"accessCode\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"p\n" +
	"\x1fGetInstanceByAccessCodeResponse\x12.\n" +
	"\binstance\x18\x01 \x01(\v2\x12.quiz.QuizInstanceR\binstance\x12\x1d\n" +
	"\n" +
	"has_access\x18\x02 \x01(\bR\thasAccess\"M\n" +
	"\x1aGetHostingInstancesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"O\n" +
	"\x1bGetHostingInstancesResponse\x120\n" +
	"\tinstances\x18\x01 \x03(\v2\x12.quiz.QuizInstanceR\tinstances\"b\n" +
	" GetParticipatingInstancesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0esession_status\x18\x02 \x01(\tR\rsessionStatus\"n\n" +
	"\x15ParticipatingInstance\x12.\n" +
	"\binstance\x18\x01 \x01(\v2\x12.quiz.QuizInstanceR\binstance\x12%\n" +
	"\x0esession_status\x18\x02 \x01(\tR\rsessionStatus\"^\n" +
	"!GetParticipatingInstancesResponse\x129\n" +
	"\tinstances\x18\x01 \x03(\v2\x1b.quiz.ParticipatingInstanceR\tinstances\"\xc5\x01\n" +
	"\x0fParticipantInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0esession_status\x18\x02 \x01(\tR\rsessionStatus\x12#\n" +
	"\rreview_status\x18\x03 \x01(\tR\freviewStatus\x12\x1f\n" +
	"\vtotal_score\x18\x04 \x01(\x05R\n" +
	"totalScore\x12,\n" +
	"\x12max_possible_score\x18\x05 \x01(\x05R\x10maxPossibleScore\"Z\n" +
	"\x1eGetInstanceParticipantsRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\\\n" +
	"\x1fGetInstanceParticipantsResponse\x129\n" +
	"\fparticipants\x18\x01 \x03(\v2\x15.quiz.ParticipantInfoR\fparticipants\"\x9e\x01\n" +
	"\n" +
	"AnswerInfo\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x03 \x01(\bR\tisCorrect\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\"\n" +
	"\rtime_spent_ms\x18\x05 \x01(\x03R\vtimeSpentMs\"\x7f\n" +
	"\x1cGetParticipantAnswersRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0eparticipant_id\x18\x03 \x01(\tR\rparticipantId\"\xa9\x01\n" +
	"\x1dGetParticipantAnswersResponse\x12.\n" +
	"\binstance\x18\x01 \x01(\v2\x12.quiz.QuizInstanceR\binstance\x12,\n" +
	"\tquestions\x18\x02 \x03(\v2\x0e.quiz.QuestionR\tquestions\x12*\n" +
	"\aanswers\x18\x03 \x03(\v2\x10.quiz.AnswerInfoR\aanswers\"\xac\x01\n" +
	"\x12GradeAnswerRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0eparticipant_id\x18\x03 \x01(\tR\rparticipantId\x12\x1f\n" +
	"\vquestion_id\x18\x04 \x01(\tR\n" +
	"questionId\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\"\x15\n" +
	"\x13GradeAnswerResponse\"Q\n" +
	"\x15PublishResultsRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x18\n" +
	"\x16PublishResultsResponse2\x9d\t\n" +
	"\vQuizService\x12K\n" +
	"\x0eCreateTemplate\x12\x1b.quiz.CreateTemplateRequest\x1a\x1c.quiz.CreateTemplateResponse\x12B\n" +
	"\vGetTemplate\x12\x18.quiz.GetTemplateRequest\x1a\x19.quiz.GetTemplateResponse\x12E\n" +
	"\fGetTemplates\x12\x19.quiz.GetTemplatesRequest\x1a\x1a.quiz.GetTemplatesResponse\x12K\n" +
	"\x0eUpdateTemplate\x12\x1b.quiz.UpdateTemplateRequest\x1a\x1c.quiz.UpdateTemplateResponse\x12K\n" +
	"\x0eDeleteTemplate\x12\x1b.quiz.DeleteTemplateRequest\x1a\x1c.quiz.DeleteTemplateResponse\x12K\n" +
	"\x0eCreateInstance\x12\x1b.quiz.CreateInstanceRequest\x1a\x1c.quiz.CreateInstanceResponse\x12B\n" +
	"\vGetInstance\x12\x18.quiz.GetInstanceRequest\x1a\x19.quiz.GetInstanceResponse\x12f\n" +
	"\x17GetInstanceByAccessCode\x12$.quiz.GetInstanceByAccessCodeRequest\x1a%.quiz.GetInstanceByAccessCodeResponse\x12Z\n" +
	"\x13GetHostingInstances\x12 .quiz.GetHostingInstancesRequest\x1a!.quiz.GetHostingInstancesResponse\x12l\n" +
	"\x19GetParticipatingInstances\x12&.quiz.GetParticipatingInstancesRequest\x1a'.quiz.GetParticipatingInstancesResponse\x12f\n" +
	"\x17GetInstanceParticipants\x12$.quiz.GetInstanceParticipantsRequest\x1a%.quiz.GetInstanceParticipantsResponse\x12`\n" +
	"\x15GetParticipantAnswers\x12\".quiz.GetParticipantAnswersRequest\x1a#.quiz.GetParticipantAnswersResponse\x12B\n" +
	"\vGradeAnswer\x12\x18.quiz.GradeAnswerRequest\x1a\x19.quiz.GradeAnswerResponse\x12K\n" +
	"\x0ePublishResults\x12\x1b.quiz.PublishResultsRequest\x1a\x1c.quiz.PublishResultsResponseB\x14Z\x12quiz-service/protob\x06proto3"

var (
	file_quiz_proto_rawDescOnce sync.Once
	file_quiz_proto_rawDescData []byte
)

func file_quiz_proto_rawDescGZIP() []byte {
	file_quiz_proto_rawDescOnce.Do(func() {
		file_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quiz_proto_rawDesc), len(file_quiz_proto_rawDesc)))
	})
	return file_quiz_proto_rawDescData
}

var file_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_quiz_proto_goTypes = []any{
	(*QuizTemplate)(nil),                      // 0: quiz.QuizTemplate
	(*QuizSyncSettings)(nil),                  // 1: quiz.QuizSyncSettings
	(*QuizAsyncSettings)(nil),                 // 2: quiz.QuizAsyncSettings
	(*SingleChoice)(nil),                      // 3: quiz.SingleChoice
	(*MultipleChoice)(nil),                    // 4: quiz.MultipleChoice
	(*OpenAnswer)(nil),                        // 5: quiz.OpenAnswer
	(*Question)(nil),                          // 6: quiz.Question
	(*QuizInstance)(nil),                      // 7: quiz.QuizInstance
	(*CreateTemplateRequest)(nil),             // 8: quiz.CreateTemplateRequest
	(*QuestionInput)(nil),                     // 9: quiz.QuestionInput
	(*CreateTemplateResponse)(nil),            // 10: quiz.CreateTemplateResponse
	(*GetTemplateRequest)(nil),                // 11: quiz.GetTemplateRequest
	(*GetTemplateResponse)(nil),               // 12: quiz.GetTemplateResponse
	(*GetTemplatesRequest)(nil),               // 13: quiz.GetTemplatesRequest
	(*TemplateWithQuestions)(nil),             // 14: quiz.TemplateWithQuestions
	(*GetTemplatesResponse)(nil),              // 15: quiz.GetTemplatesResponse
	(*UpdateTemplateRequest)(nil),             // 16: quiz.UpdateTemplateRequest
	(*UpdateTemplateResponse)(nil),            // 17: quiz.UpdateTemplateResponse
	(*DeleteTemplateRequest)(nil),             // 18: quiz.DeleteTemplateRequest
	(*DeleteTemplateResponse)(nil),            // 19: quiz.DeleteTemplateResponse
	(*CreateInstanceRequest)(nil),             // 20: quiz.CreateInstanceRequest
	(*CreateInstanceResponse)(nil),            // 21: quiz.CreateInstanceResponse
	(*GetInstanceRequest)(nil),                // 22: quiz.GetInstanceRequest
	(*GetInstanceResponse)(nil),               // 23: quiz.GetInstanceResponse
	(*GetInstanceByAccessCodeRequest)(nil),    // 24: quiz.GetInstanceByAccessCodeRequest
	(*GetInstanceByAccessCodeResponse)(nil),   // 25: quiz.GetInstanceByAccessCodeResponse
	(*GetHostingInstancesRequest)(nil),        // 26: quiz.GetHostingInstancesRequest
	(*GetHostingInstancesResponse)(nil),       // 27: quiz.GetHostingInstancesResponse
	(*GetParticipatingInstancesRequest)(nil),  // 28: quiz.GetParticipatingInstancesRequest
	(*ParticipatingInstance)(nil),             // 29: quiz.ParticipatingInstance
	(*GetParticipatingInstancesResponse)(nil), // 30: quiz.GetParticipatingInstancesResponse
	(*ParticipantInfo)(nil),                   // 31: quiz.ParticipantInfo
	(*GetInstanceParticipantsRequest)(nil),    // 32: quiz.GetInstanceParticipantsRequest
	(*GetInstanceParticipantsResponse)(nil),   // 33: quiz.GetInstanceParticipantsResponse
	(*AnswerInfo)(nil),                        // 34: quiz.AnswerInfo
	(*GetParticipantAnswersRequest)(nil),      // 35: quiz.GetParticipantAnswersRequest
	(*GetParticipantAnswersResponse)(nil),     // 36: quiz.GetParticipantAnswersResponse
	(*GradeAnswerRequest)(nil),                // 37: quiz.GradeAnswerRequest
	(*GradeAnswerResponse)(nil),               // 38: quiz.GradeAnswerResponse
	(*PublishResultsRequest)(nil),             // 39: quiz.PublishResultsRequest
	(*PublishResultsResponse)(nil),            // 40: quiz.PublishResultsResponse
	(*timestamppb.Timestamp)(nil),             // 41: google.protobuf.Timestamp
}
var file_quiz_proto_depIdxs = []int32{
	41, // 0: quiz.QuizTemplate.created_at:type_name -> google.protobuf.Timestamp
	41, // 1: quiz.QuizTemplate.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: quiz.QuizTemplate.sync_settings:type_name -> quiz.QuizSyncSettings
	2,  // 3: quiz.QuizTemplate.async_settings:type_name -> quiz.QuizAsyncSettings
	3,  // 4: quiz.Question.single_choice:type_name -> quiz.SingleChoice
	4,  // 5: quiz.Question.multiple_choice:type_name -> quiz.MultipleChoice
	5,  // 6: quiz.Question.open_answer:type_name -> quiz.OpenAnswer
	41, // 7: quiz.QuizInstance.created_at:type_name -> google.protobuf.Timestamp
	41, // 8: quiz.QuizInstance.start_time:type_name -> google.protobuf.Timestamp
	41, // 9: quiz.QuizInstance.deadline:type_name -> google.protobuf.Timestamp
	1,  // 10: quiz.QuizInstance.sync_settings:type_name -> quiz.QuizSyncSettings
	2,  // 11: quiz.QuizInstance.async_settings:type_name -> quiz.QuizAsyncSettings
	9,  // 12: quiz.CreateTemplateRequest.questions:type_name -> quiz.QuestionInput
	1,  // 13: quiz.CreateTemplateRequest.sync_settings:type_name -> quiz.QuizSyncSettings
	2,  // 14: quiz.CreateTemplateRequest.async_settings:type_name -> quiz.QuizAsyncSettings
	3,  // 15: quiz.QuestionInput.single_choice:type_name -> quiz.SingleChoice
	4,  // 16: quiz.QuestionInput.multiple_choice:type_name -> quiz.MultipleChoice
	5,  // 17: quiz.QuestionInput.open_answer:type_name -> quiz.OpenAnswer
	0,  // 18: quiz.CreateTemplateResponse.template:type_name -> quiz.QuizTemplate
	6,  // 19: quiz.CreateTemplateResponse.questions:type_name -> quiz.Question
	0,  // 20: quiz.GetTemplateResponse.template:type_name -> quiz.QuizTemplate
	6,  // 21: quiz.GetTemplateResponse.questions:type_name -> quiz.Question
	0,  // 22: quiz.TemplateWithQuestions.template:type_name -> quiz.QuizTemplate
	6,  // 23: quiz.TemplateWithQuestions.questions:type_name -> quiz.Question
	14, // 24: quiz.GetTemplatesResponse.templates:type_name -> quiz.TemplateWithQuestions
	9,  // 25: quiz.UpdateTemplateRequest.questions:type_name -> quiz.QuestionInput
	1,  // 26: quiz.UpdateTemplateRequest.sync_settings:type_name -> quiz.QuizSyncSettings
	2,  // 27: quiz.UpdateTemplateRequest.async_settings:type_name -> quiz.QuizAsyncSettings
	0,  // 28: quiz.UpdateTemplateResponse.template:type_name -> quiz.QuizTemplate
	6,  // 29: quiz.UpdateTemplateResponse.questions:type_name -> quiz.Question
	41, // 30: quiz.CreateInstanceRequest.deadline:type_name -> google.protobuf.Timestamp
	7,  // 31: quiz.CreateInstanceResponse.instance:type_name -> quiz.QuizInstance
	7,  // 32: quiz.GetInstanceResponse.instance:type_name -> quiz.QuizInstance
	6,  // 33: quiz.GetInstanceResponse.questions:type_name -> quiz.Question
	7,  // 34: quiz.GetInstanceByAccessCodeResponse.instance:type_name -> quiz.QuizInstance
	7,  // 35: quiz.GetHostingInstancesResponse.instances:type_name -> quiz.QuizInstance
	7,  // 36: quiz.ParticipatingInstance.instance:type_name -> quiz.QuizInstance
	29, // 37: quiz.GetParticipatingInstancesResponse.instances:type_name -> quiz.ParticipatingInstance
	31, // 38: quiz.GetInstanceParticipantsResponse.participants:type_name -> quiz.ParticipantInfo
	7,  // 39: quiz.GetParticipantAnswersResponse.instance:type_name -> quiz.QuizInstance
	6,  // 40: quiz.GetParticipantAnswersResponse.questions:type_name -> quiz.Question
	34, // 41: quiz.GetParticipantAnswersResponse.answers:type_name -> quiz.AnswerInfo
	8,  // 42: quiz.QuizService.CreateTemplate:input_type -> quiz.CreateTemplateRequest
	11, // 43: quiz.QuizService.GetTemplate:input_type -> quiz.GetTemplateRequest
	13, // 44: quiz.QuizService.GetTemplates:input_type -> quiz.GetTemplatesRequest
	16, // 45: quiz.QuizService.UpdateTemplate:input_type -> quiz.UpdateTemplateRequest
	18, // 46: quiz.QuizService.DeleteTemplate:input_type -> quiz.DeleteTemplateRequest
	20, // 47: quiz.QuizService.CreateInstance:input_type -> quiz.CreateInstanceRequest
	22, // 48: quiz.QuizService.GetInstance:input_type -> quiz.GetInstanceRequest
	24, // 49: quiz.QuizService.GetInstanceByAccessCode:input_type -> quiz.GetInstanceByAccessCodeRequest
	26, // 50: quiz.QuizService.GetHostingInstances:input_type -> quiz.GetHostingInstancesRequest
	28, // 51: quiz.QuizService.GetParticipatingInstances:input_type -> quiz.GetParticipatingInstancesRequest
	32, // 52: quiz.QuizService.GetInstanceParticipants:input_type -> quiz.GetInstanceParticipantsRequest
	35, // 53: quiz.QuizService.GetParticipantAnswers:input_type -> quiz.GetParticipantAnswersRequest
	37, // 54: quiz.QuizService.GradeAnswer:input_type -> quiz.GradeAnswerRequest
	39, // 55: quiz.QuizService.PublishResults:input_type -> quiz.PublishResultsRequest
	10, // 56: quiz.QuizService.CreateTemplate:output_type -> quiz.CreateTemplateResponse
	12, // 57: quiz.QuizService.GetTemplate:output_type -> quiz.GetTemplateResponse
	15, // 58: quiz.QuizService.GetTemplates:output_type -> quiz.GetTemplatesResponse
	17, // 59: quiz.QuizService.UpdateTemplate:output_type -> quiz.UpdateTemplateResponse
	19, // 60: quiz.QuizService.DeleteTemplate:output_type -> quiz.DeleteTemplateResponse
	21, // 61: quiz.QuizService.CreateInstance:output_type -> quiz.CreateInstanceResponse
	23, // 62: quiz.QuizService.GetInstance:output_type -> quiz.GetInstanceResponse
	25, // 63: quiz.QuizService.GetInstanceByAccessCode:output_type -> quiz.GetInstanceByAccessCodeResponse
	27, // 64: quiz.QuizService.GetHostingInstances:output_type -> quiz.GetHostingInstancesResponse
	30, // 65: quiz.QuizService.GetParticipatingInstances:output_type -> quiz.GetParticipatingInstancesResponse
	33, // 66: quiz.QuizService.GetInstanceParticipants:output_type -> quiz.GetInstanceParticipantsResponse
	36, // 67: quiz.QuizService.GetParticipantAnswers:output_type -> quiz.GetParticipantAnswersResponse
	38, // 68: quiz.QuizService.GradeAnswer:output_type -> quiz.GradeAnswerResponse
	40, // 69: quiz.QuizService.PublishResults:output_type -> quiz.PublishResultsResponse
	56, // [56:70] is the sub-list for method output_type
	42, // [42:56] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_quiz_proto_init() }
func file_quiz_proto_init() {
	if File_quiz_proto != nil {
		return
	}
	file_quiz_proto_msgTypes[0].OneofWrappers = []any{
		(*QuizTemplate_SyncSettings)(nil),
		(*QuizTemplate_AsyncSettings)(nil),
	}
	file_quiz_proto_msgTypes[6].OneofWrappers = []any{
		(*Question_SingleChoice)(nil),
		(*Question_MultipleChoice)(nil),
		(*Question_OpenAnswer)(nil),
	}
	file_quiz_proto_msgTypes[7].OneofWrappers = []any{
		(*QuizInstance_SyncSettings)(nil),
		(*QuizInstance_AsyncSettings)(nil),
	}
	file_quiz_proto_msgTypes[8].OneofWrappers = []any{
		(*CreateTemplateRequest_SyncSettings)(nil),
		(*CreateTemplateRequest_AsyncSettings)(nil),
	}
	file_quiz_proto_msgTypes[9].OneofWrappers = []any{
		(*QuestionInput_SingleChoice)(nil),
		(*QuestionInput_MultipleChoice)(nil),
		(*QuestionInput_OpenAnswer)(nil),
	}
	file_quiz_proto_msgTypes[16].OneofWrappers = []any{
		(*UpdateTemplateRequest_SyncSettings)(nil),
		(*UpdateTemplateRequest_AsyncSettings)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quiz_proto_rawDesc), len(file_quiz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quiz_proto_goTypes,
		DependencyIndexes: file_quiz_proto_depIdxs,
		MessageInfos:      file_quiz_proto_msgTypes,
	}.Build()
	File_quiz_proto = out.File
	file_quiz_proto_goTypes = nil
	file_quiz_proto_depIdxs = nil
}
