CREATE TABLE IF NOT EXISTS ai_bans (
    user_id VARCHAR(255) PRIMARY KEY,
    reason TEXT NOT NULL DEFAULT '',
    banned_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
